### ISSUE TITLE
License

### ISSUE THREAD

**Issue by geekuillaume** [carloscuesta/carloscuesta.me#502]
Hi Carlos !
I've seen that the package.json indicate that the code is released under MIT license but there is no LICENSE file. How open are you to let other use your code for their own website? My website needs some refreshing, I was looking for inspiration and yours is the best I've seen here. I don't need all the features (I don't write blog post) but I can definitely help with other features if needed.

**Comment by carloscuesta** [comment]
Hey @geekuillaume  👋🏼 

Thanks for asking! I was not aware that I was missing the license file! 

- Feel free to use the code as you want 😊 
- Do not copy-cat the same exact design 🙏🏼 
- Credit is much appreciated ❤️ 

Enjoy!
